services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./monitoring/prometheus/alerts.yml:/etc/prometheus/rules/alerts.yml:ro
      - ./monitoring/prometheus/test_fire_rule.yml:/etc/prometheus/rules/test_fire_rule.yml:ro
      - prometheus_data:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9090:9090"
    networks:
      - transcendence-net
    restart: unless-stopped
    command:
      - '--storage.tsdb.retention.time=15d' # Retain data for 15 days
      - '--config.file=/etc/prometheus/prometheus.yml'

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
      - ./monitoring/alertmanager/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    environment:
      SLACK_WEBHOOK_URL: ${SLACK_WEBHOOK_URL}
    entrypoint: [ "/docker-entrypoint.sh" ]
    command:
      - '--log.level=info'
    networks:
      - transcendence-net
    restart: unless-stopped

  grafana:
    # Grafana for visualizing Prometheus data
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - transcendence-net
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_AUTH_ANONYMOUS_ENABLED: ${GF_AUTH_ANONYMOUS_ENABLED}
      GF_USERS_ALLOW_SIGN_UP: ${GF_USERS_ALLOW_SIGN_UP}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./services/nginx/ssl:/etc/nginx/ssl:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - frontend
      - backend
    networks:
      - transcendence-net

  nginx-exporter:
    # Prometheus exporter for Nginx
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - -nginx.scrape-uri=http://nginx:80/stub_status
    ports:
      - "9113:9113"
    networks:
      - transcendence-net
    depends_on:
      - nginx

  frontend:
    build:
      context: .
      dockerfile: ./services/frontend/Dockerfile
    container_name: frontend
    volumes:
      - ./services/frontend:/app/services/frontend
      - ./packages/shared:/app/packages/shared
    ports:
      - "5173:5173"
    networks:
      - transcendence-net

  backend:
    build:
      context: .
      dockerfile: ./services/backend/Dockerfile
    container_name: backend
    networks:
      - transcendence-net
    ports:
      - "3000:3000"
    volumes:
      - ./services/backend/data:/app/services/backend/data
      # - backend_data:/app
    environment:
      JWT_SECRET: ${JWT_SECRET}
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  prometheus_data:
  frontend_node_modules:
  backend_data:
  grafana_data:


secrets:
  grafana_admin_password:
    file: ./monitoring/grafana/secrets/grafana_admin_password

networks:
  transcendence-net:
    driver: bridge
